version: '3.5'
services:
  api:
    build:
      context: ./
    restart: unless-stopped
    ports:
      - 8082:8082
    env_file:
      - db.env

networks:
  default:
    external: true
    name: indexer_net